# Generated by Django 3.0.7 on 2020-07-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0002_auto_20200704_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.CharField(default='Not Mentioned', max_length=200),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(default='Not Mentioned', max_length=400),
        ),
        migrations.AddField(
            model_name='ad',
            name='pin_code',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='ad',
            name='state',
            field=models.CharField(default='Not Mentioned', max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_description',
            field=models.CharField(default='Not Mentioned', max_length=900),
        ),
    ]
