# Generated by Django 3.0.7 on 2020-07-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0003_auto_20200708_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='city',
            new_name='ad_city',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='location',
            new_name='ad_location',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='pin_code',
            new_name='ad_pin_code',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='state',
            new_name='ad_state',
        ),
    ]
