# Generated by Django 3.0.7 on 2020-07-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ad_review',
            new_name='message',
        ),
    ]
